---
outdir: #output directory relative to Gruntfile
  dev: _dev_public
  prod: ../gh-pages

assetdirs:

src: #Order and location of source files
  js:
    vendor: 
      - components/jquery/jquery.js
      - components/angular/angular.js
      - components/angular-resource/angular-resource.js
      - components/angular-cookies/angular-cookies.js
      - components/bootstrap/js/bootstrap-tooltip.js
      - components/bootstrap/js/bootstrap-popover.js
      - components/bootstrap/js/bootstrap-modal.js
      - ../angular-personal/dist/angular-personal-complete.js
#      - components/angular-personal/dist/angular-personal-complete.js

nomangle: #keywords to except from minifiers
  - jQuery
  - angular
...
