---
outdir: #output directory relative to Gruntfile
  dev: _dev_public
  prod: ../gh-pages

src: #Order and location of source files
  js:
    vendor: 
      - components/jquery/jquery.js
      - components/bootstrap/js/bootstrap-tooltip.js
      - components/bootstrap/js/bootstrap-popover.js

nomangle: #keywords to except from minifiers
  - jQuery
...